/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankAccount;

import java.awt.*;
import java.awt.event.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.io.*;
import java.util.ArrayList;
/**
 *
 * @author SOUMALYA
 */
public class BankMain extends javax.swing.JFrame implements java.io.Serializable {
    static double limit = 1000;
    admin Admin = new admin("ufukbasural@uralnet.com", "ufukUral");
    ArrayList<Account> accounts = new ArrayList<>();
    /**
     * Creates new form BankMain
     */
    public BankMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        jButton1 = new JButton();
        jLabel1 = new JLabel();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jButton6 = new JButton();
        jButton7 = new JButton();
        jButton8 = new JButton();
        jButton5 = new JButton();
        jButton9 = new JButton();
        jMenuBar1 = new JMenuBar();

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("URAL BANK ONLİNE BİLGİ SİSTEMİ");

        jButton1.setText("Hesap Açma");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new Font("Microsoft Sans Serif", 1, 15)); // NOI18N
        jLabel1.setText("                     URAL BANK ONLİNE BİLGİ SİSTEMİNE HOŞGELDİNİZ");

        jButton2.setText("Para Yatırma");
        jButton2.setMaximumSize(new Dimension(107, 23));
        jButton2.setMinimumSize(new Dimension(107, 23));
        jButton2.setPreferredSize(new Dimension(107, 23));
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Para Çekme");
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hesap Bilgi Görüntüleme");
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Para Aktar");
        jButton6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("ÇIKIŞ");
        jButton7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Yönetici Girişi");
        jButton8.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setText("Kredi İşlemi");
        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setText("Giriş Yap");
        jButton9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton6, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(jButton9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton7, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton6, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Account acc;
    
    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
           double num1;
           String num;
           
           while(true){
               num = JOptionPane.showInputDialog(null, "Yatırılacak Para Miktarını Giriniz:", "Para Yatırma", 1);
               num1 = Double.parseDouble(num);
               if(num1 < 0){
                       JOptionPane.showMessageDialog(null, "Para Negatif Olamaz", "Para Çekme", 1);
                   }
               else if(limit < num1){
                   JOptionPane.showMessageDialog(null, "Limiti aşıyor. Limit:" + limit);
               }
               else break;
           }
           acc.deposit(num1);
        }
        catch(NumberFormatException | NullPointerException nfe1)
        {
            JOptionPane.showMessageDialog(null, nfe1, "Error", 2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
        @SuppressWarnings("unchecked")
    private void jButton6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String tc = JOptionPane.showInputDialog(null,"Parayı Aktarmak İstediğiniz Kişinin Tc Kimlik Numarasını Giriniz: ", "Para Aktarma", 1);
        String num;
        double num1;
        boolean isBreak = false;
        for(Account a : accounts){
            if(a.getTcNo().equals(tc)){
                while(true){
                num = JOptionPane.showInputDialog(null,"Ne Kadar Para Aktarmak İstediğinizi Giriniz: ", "Para Aktarma", 1);
                num1 = Double.parseDouble(num);
                if(num1 > limit) JOptionPane.showMessageDialog(null,"Lütfen Limit Değerinden Daha Az Miktar Giriniz. Limit: " + limit, "Para Aktarma", 1);
                else break;
                }
                try {
                    acc.withdraw(num1);
                } catch (BankAccountException ex) {
                    Logger.getLogger(BankMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                a.deposit(num1);
                isBreak = true;
                break;
                
            }
        }
        if(!isBreak){
            JOptionPane.showMessageDialog(null,"Böyle Bir Hesap Yok", "Para Aktarma", 1);
        }
        else{
            JOptionPane.showMessageDialog(null,"Para Başarılı Bir Şekilde Aktarıldı", "Para Aktarma", 1);

        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean isBreak = true;
        String name;
        String tcNum;
        String phoneNum;
        String email;
        long num; 
        name = JOptionPane.showInputDialog(null, "Lütfen hesap sahibinin isim soyismini giriniz:", "Hesap Oluştur", 1);
        while(true){
            tcNum = JOptionPane.showInputDialog(null, "Lütfen Tc Kimlik Numaranızı Giriniz", "Hesap Oluştur", 1);
            if(tcNum.length() == 11){
                for(int i = 0; i < 11; i++){
                    if('1' != tcNum.charAt(i) && '2' != tcNum.charAt(i) && '3' != tcNum.charAt(i) && '4' != tcNum.charAt(i) && '5' != tcNum.charAt(i) && '6' != tcNum.charAt(i) && '7' != tcNum.charAt(i) && '8' != tcNum.charAt(i) && '9' != tcNum.charAt(i) && '0' != tcNum.charAt(i)){
                        JOptionPane.showMessageDialog(null, "Lütfen Doğru Bir Tc Kimlik Numarası Giriniz", "Hesap Oluştur", 1);
                        isBreak = false;
                        break;
                    }
                }
                if(isBreak) break;
            }
            else{
                JOptionPane.showMessageDialog(null, "Lütfen Doğru Bir Tc Kimlik Numarası Giriniz", "Hesap Oluştur", 1);
            }
            
        }
        email = JOptionPane.showInputDialog(null, "E-posta Adresinizi Giriniz:", "Hesap Oluştur", 1);
        isBreak = true;
        while(true){
            phoneNum = JOptionPane.showInputDialog(null, "10 Haneli Telefon Numaranızı Giriniz:", "Hesap Oluştur", 1);
            if(phoneNum.length() == 10){
                for(int i = 0; i < 10; i++){
                    if('1' != phoneNum.charAt(i) && '2' != phoneNum.charAt(i) && '3' != phoneNum.charAt(i) && '4' != phoneNum.charAt(i) && '5' != phoneNum.charAt(i) && '6' != phoneNum.charAt(i) && '7' != phoneNum.charAt(i) && '8' != phoneNum.charAt(i) && '9' != phoneNum.charAt(i) && '0' != phoneNum.charAt(i)){
                        JOptionPane.showMessageDialog(null, "Lütfen Doğru Bir Şekilde Telefon Numrası Giriniz", "Hesap Oluştur", 1);
                        isBreak = false;
                        break;
                    }
                }
                if(isBreak) break;
            }
            else{
                JOptionPane.showMessageDialog(null, "Lütfen Doğru Bir Şekilde Telefon Numrası Giriniz", "Hesap Oluştur", 1);
            }
        }
        num = 1332522123;
        acc = new Account(name, num, phoneNum, email, tcNum);
        accounts.add(acc);
        JOptionPane.showMessageDialog(null, "Hesap Başarılı Bir Şekilde Oluşturuldu!", "Hesap Oluştur", 1);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
           {
               double num1;
               String num;
               while(true){
                   num = JOptionPane.showInputDialog(null, "Çekilecek Para Miktarını Giriniz:", "Para Çekme", 1);
                   num1 = Double.parseDouble(num);
                   if(num1 > acc.getBalance()) JOptionPane.showMessageDialog(null, "Bakiye Yetersiz:", "Para Çekme", 1);
                   else if(limit < num1) JOptionPane.showMessageDialog(null, "Limiti aşıyor. Limit: "+limit, "Para Çekme", 1);
                   else break;
               }
               
               acc.withdraw(num1);
           }
           catch(BankAccountException | NumberFormatException | NullPointerException ex)
           {
               JOptionPane.showMessageDialog(null, ex, "Error", 2);
           }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try
       {
         double num = acc.getBalance();
         if(acc.getHaveLoan()) JOptionPane.showMessageDialog(null, "Mevcut Bakiye : " + num + "\n"+ acc.getLoan(), "Mevcut Bakiye", 1);
         else JOptionPane.showMessageDialog(null, "Mevcut Bakiye : " + num, "Mevcut Bakiye", 1);
       }
       catch(NullPointerException npe)
       {
           JOptionPane.showMessageDialog(null, npe, "Error", 2);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String email;
        String password;
        while(true){
            email = JOptionPane.showInputDialog(null, "Yönetici E-postanızı Giriniz:", "Yönetici Girişi", 1);
            password = JOptionPane.showInputDialog(null, "Yönetici Şifrenizi Giriniz:", "Yönetici Girişi", 1);
            if(!email.equals(Admin.getEmail()) || !password.equals(Admin.getPassword())){
                JOptionPane.showMessageDialog(null, "Yönetici E-postanızı Veya Şifrenizi Yanlış Girdiniz", "Yönetici Girişi", 1);
            }
            else break;
        }
        try {
            String num;
            num = JOptionPane.showInputDialog(null, "Yeni Limiti Belirleyiniz:", "Create Account", 1);
            limit= Double.parseDouble(num);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e, "Error", 2);

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String loan;
        String num;
        boolean isBreak = false;
        double num1;
        acc.setHaveLoan(true);
        while(!isBreak){
            loan = JOptionPane.showInputDialog(null, "Aşağıdaki Planlardan Birini Seçiniz\n1.        3 AY TAKSİT VADE FARKI YOK.\n2.         6 AY TAKSİT %5 VADE FARKI\n3.       12 AY TAKSİT %10 VADE FARKI", "Kredi işlemi", 1);
            if("1".equals(loan)){
                num = JOptionPane.showInputDialog(null, "Çekmek İstediğiniz Kredi Miktarını Giriniz.", "Kredi İşlemleri", 1);
                num1 = Double.parseDouble(num);
                if(num1 > acc.getLimit()){
                    JOptionPane.showMessageDialog(null, "Kredi Limitini Aşıyor. Limit: "+ acc.getLimit(), "Kredi İşlemleri", 1);
                }
                else{
                    acc.setLoan(num1, 0, 3);
                    isBreak = true;
                    
                }
            }
            
            else if("2".equals(loan)){
                num = JOptionPane.showInputDialog(null, "Çekmek İstediğiniz Kredi Miktarını Giriniz.", "Kredi İşlemleri", 1);
                num1 = Double.parseDouble(num);
                if(num1 > acc.getLimit()){
                    JOptionPane.showMessageDialog(null, "Kredi Limitini Aşıyor. Limit: "+ acc.getLimit(), "Kredi İşlemleri", 1);
                }
                else{
                    acc.setLoan(num1, 5, 6);
                    isBreak = true;
                }
                
            }        
            else if("3".equals(loan)){
                num = JOptionPane.showInputDialog(null, "Çekmek İstediğiniz Kredi Miktarını Giriniz.", "Kredi İşlemleri", 1);
                num1 = Double.parseDouble(num);
                if(num1 > acc.getLimit()){
                    JOptionPane.showMessageDialog(null, "Kredi Limitini Aşıyor. Limit: "+ acc.getLimit(), "Kredi İşlemleri", 1);
                }
                else{
                    acc.setLoan(num1, 10, 12);
                    isBreak = true;
                }
                
            }            
            else {
                JOptionPane.showMessageDialog(null, "Doğru İşlem Seçiniz", "Kredi İşlemleri", 1);
            }
        }            

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String tc = JOptionPane.showInputDialog(null, "Giriş Yapmak İstediğiniz Hesabın Tc Numarasını Giriniz", "Giriş", 1);
        boolean isBreak = false;
        for(Account a: accounts){
            if(a.getTcNo().equals(tc)) {
                acc = a;
                isBreak = true;
                break;
            }
        }
        if(!isBreak) JOptionPane.showMessageDialog(null, "Böyle Bir Hesap Yok", "Giriş", 1);
        else{
            JOptionPane.showMessageDialog(null, "Başarılı Bir Şekilde Giriş Yapıldı", "Giriş", 1);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 4) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BankMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JButton jButton8;
    private JButton jButton9;
    private JLabel jLabel1;
    private JMenuBar jMenuBar1;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
